"""
Script to generate images from prompts using Nano Banana.
Uses prompts generated by the post generation engine.
"""

import sys
import json
import time
from pathlib import Path
from typing import List, Dict

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from modules.post_generation_engine import create_engine
from modules.nano_banana_client import create_nano_banana_client

# ============================================================================
# CONFIGURATION
# ============================================================================

# PromoCanon directory
CANON_DIRECTORY = "PromoCanon_Show_33adb096b04ecd6b23ce9341160b199f2d489311_1_100"

# Generation settings (same as debug script)
EPISODE_NUM = 7
EPISODE_CHARACTER = None
PROMPTS_PER_CLIFFHANGER = 3

# Nano Banana settings
GCP_PROJECT_ID = None  # Uses from creds.py if None
GCP_REGION = "us-central1"
IMAGE_WIDTH = 1024
IMAGE_HEIGHT = 1024
IMAGE_STYLE = "cinematic"  # Optional style parameter

# GCS settings (optional - for storing generated images)
GCS_BUCKET_NAME = None  # Set to bucket name if you want to upload to GCS
GCS_UPLOAD = False  # Set to True to upload images to GCS

# Output settings
SAVE_RESULTS = True
RESULTS_FILE = "generated_images.json"
MAX_IMAGES_TO_GENERATE = 3  # Limit for testing


def generate_images_from_prompts():
    """Generate images from prompts"""
    print("="*80)
    print("NANO BANANA IMAGE GENERATION")
    print("="*80)
    print(f"Canon Directory: {CANON_DIRECTORY}")
    print(f"Episode: {EPISODE_NUM}")
    print(f"Prompts per cliffhanger: {PROMPTS_PER_CLIFFHANGER}")
    print(f"Max images to generate: {MAX_IMAGES_TO_GENERATE}")
    print(f"Image size: {IMAGE_WIDTH}x{IMAGE_HEIGHT}")
    print("="*80)
    
    # Initialize post generation engine
    try:
        print("\n1. Initializing post generation engine...")
        engine = create_engine(CANON_DIRECTORY)
        print("   ✓ Engine initialized")
    except Exception as e:
        print(f"   ✗ Error: {e}")
        return
    
    # Generate prompts
    try:
        print(f"\n2. Generating prompts for Episode {EPISODE_NUM}...")
        prompts = engine.generate_prompts_for_cliffhanger(
            episode_num=EPISODE_NUM,
            perspective_character=EPISODE_CHARACTER,
            prompts_per_cliffhanger=PROMPTS_PER_CLIFFHANGER
        )
        print(f"   ✓ Generated {len(prompts)} prompts")
        
        if not prompts:
            print("   ⚠ No prompts generated. Exiting.")
            return
        
        # Limit to max images
        prompts = prompts[:MAX_IMAGES_TO_GENERATE]
        print(f"   → Using first {len(prompts)} prompts for image generation")
        
    except Exception as e:
        print(f"   ✗ Error generating prompts: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # Initialize Nano Banana client
    try:
        print("\n3. Initializing Nano Banana client...")
        client = create_nano_banana_client(
            project_id=GCP_PROJECT_ID,
            region=GCP_REGION
        )
        print("   ✓ Client initialized")
    except Exception as e:
        print(f"   ✗ Error initializing client: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # Generate images
    print(f"\n4. Generating {len(prompts)} images...")
    print("   (This may take a few seconds per image)")
    print("-"*80)
    
    results = []
    
    for i, prompt_data in enumerate(prompts, 1):
        prompt_text = prompt_data.get('prompt', '')
        episode = prompt_data.get('episode', 'Unknown')
        perspective = prompt_data.get('perspective_character', 'Generic')
        
        print(f"\n   Image {i}/{len(prompts)}")
        print(f"   Episode: {episode}")
        print(f"   Perspective: {perspective}")
        print(f"   Prompt: {prompt_text[:100]}...")
        
        try:
            # Generate image
            result = client.generate_image(
                prompt=prompt_text,
                width=IMAGE_WIDTH,
                height=IMAGE_HEIGHT,
                style=IMAGE_STYLE
            )
            
            if result.get('status') == 'completed':
                image_url = result.get('image_url')
                image_id = result.get('image_id')
                
                print(f"   ✓ Image generated successfully")
                print(f"   Image ID: {image_id}")
                print(f"   Image URL: {image_url}")
                
                # Upload to GCS if configured
                gcs_url = None
                if GCS_UPLOAD and GCS_BUCKET_NAME and image_url:
                    try:
                        print(f"   Uploading to GCS...")
                        blob_name = f"images/episode_{episode}/{image_id}.png"
                        gcs_url = client.upload_to_gcs(
                            image_url=image_url,
                            bucket_name=GCS_BUCKET_NAME,
                            blob_name=blob_name
                        )
                        print(f"   ✓ Uploaded to: {gcs_url}")
                    except Exception as e:
                        print(f"   ⚠ GCS upload failed: {e}")
                
                # Store result
                image_result = {
                    'prompt_data': prompt_data,
                    'image_id': image_id,
                    'image_url': image_url,
                    'gcs_url': gcs_url,
                    'status': 'completed',
                    'generated_at': time.time()
                }
                results.append(image_result)
                
            elif result.get('status') == 'error':
                print(f"   ✗ Error: {result.get('error')}")
                results.append({
                    'prompt_data': prompt_data,
                    'status': 'error',
                    'error': result.get('error'),
                    'generated_at': time.time()
                })
            else:
                print(f"   ⚠ Unexpected status: {result.get('status')}")
                results.append({
                    'prompt_data': prompt_data,
                    'status': result.get('status'),
                    'generated_at': time.time()
                })
                
        except Exception as e:
            print(f"   ✗ Exception: {e}")
            import traceback
            traceback.print_exc()
            results.append({
                'prompt_data': prompt_data,
                'status': 'exception',
                'error': str(e),
                'generated_at': time.time()
            })
        
        # Small delay between requests
        if i < len(prompts):
            print("   Waiting 1 second before next image...")
            time.sleep(1)
    
    # Save results
    if SAVE_RESULTS and results:
        print(f"\n5. Saving results to {RESULTS_FILE}...")
        try:
            output_data = {
                'generation_config': {
                    'canon_directory': CANON_DIRECTORY,
                'episode_num': EPISODE_NUM,
                'prompts_per_cliffhanger': PROMPTS_PER_CLIFFHANGER,
                'max_images': MAX_IMAGES_TO_GENERATE,
                'image_size': f"{IMAGE_WIDTH}x{IMAGE_HEIGHT}"
                },
                'results': results,
                'summary': {
                    'total': len(results),
                    'completed': len([r for r in results if r.get('status') == 'completed']),
                    'failed': len([r for r in results if r.get('status') in ['error', 'exception']])
                }
            }
            
            with open(RESULTS_FILE, 'w', encoding='utf-8') as f:
                json.dump(output_data, f, indent=2, ensure_ascii=False)
            
            print(f"   ✓ Results saved")
        except Exception as e:
            print(f"   ⚠ Failed to save results: {e}")
    
    # Summary
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    print(f"Total images attempted: {len(results)}")
    print(f"Completed: {len([r for r in results if r.get('status') == 'completed'])}")
    print(f"Failed: {len([r for r in results if r.get('status') in ['error', 'exception']])}")
    print("="*80)
    
    # Print image URLs
    completed = [r for r in results if r.get('status') == 'completed']
    if completed:
        print("\nGenerated Images:")
        for i, result in enumerate(completed, 1):
            print(f"\n  {i}. Episode {result['prompt_data'].get('episode')} - {result['prompt_data'].get('perspective_character', 'Generic')}")
            print(f"     Image ID: {result.get('image_id')}")
            print(f"     URL: {result.get('image_url')}")
            if result.get('gcs_url'):
                print(f"     GCS: {result.get('gcs_url')}")


if __name__ == "__main__":
    generate_images_from_prompts()
